######################## default configuration ####################
baseURL = "https://FOSS4G-2024-Belem.github.io/webpage/"
title = "FOSS4G 2024"
theme = "eventre-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "Lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/font-awesome/css/all.min.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/mixitup/mixitup.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = ""


####################### navigation ##########################

# new navigation
[[menu.main]]
identifier = "home"
name = "Home"
url = ""
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 2

    [[menu.main]]
    identifier = "committees"
    parent = "about"
    name = "Committees"
    url = "committees/"
    weight = 1

    [[menu.main]]
    identifier = "faq"
    parent = "about"
    name = "Frequently Asked Questions (FAQ)"
    url = "faq/"
    weight = 2

    [[menu.main]]
    identifier = "branding"
    parent = "about"
    name = "Branding"
    url = "branding/"
    weight = 3

    [[menu.main]]
    identifier = "code-of-conduct"
    parent = "about"
    name = "Code of Conduct"
    url = "code-of-conduct/"
    weight = 4

    [[menu.main]]
    identifier = "privacy-policy"
    parent = "about"
    name = "Privacy Policy"
    url = "privacy-policy/"
    weight = 5

[[menu.main]]
identifier = "registration"
name = "Regstration"
url = "regstration/"
weight = 5

    [[menu.main]]
    identifier = "visa-info"
    parent = "registration"
    name = "Visa Info"
    url = "visa-info/"
    weight = 1

    [[menu.main]]
    identifier = "travel-grant"
    parent = "registration"
    name = "Travel Grant Program"
    url = "travel-grant-program/"
    weight = 2

[[menu.main]]
identifier = "schedule"
name = "Schedule"
url = "schedule/"
weight = 5

    [[menu.main]]
    identifier = "b2b-dynamics"
    parent = "schedule"
    name = "B2B Dynamics"
    url = "b2b-dynamics/"
    weight = 1

    [[menu.main]]
    identifier = "geochicas"
    parent = "schedule"
    name = "GeoChicas & Meninas da Geo"
    url = "geochicas-meninas-da-geo/"
    weight = 2

    [[menu.main]]
    identifier = "community-sprint"
    parent = "schedule"
    name = "Community Sprint"
    url = "community-sprint/"
    weight = 3

    [[menu.main]]
    identifier = "social-events"
    parent = "schedule"
    name = "Social Events"
    url = "social-events/"
    weight = 4

[[menu.main]]
identifier = "sponsors"
name = "Sponsors"
url = "sponsors/"
weight = 6

[[menu.main]]
identifier = "attending"
name = "Attending"
url = "attending/"
weight = 7

    [[menu.main]]
    identifier = "venue"
    parent = "attending"
    name = "Venue"
    url = "venue/"
    weight = 1

    [[menu.main]]
    identifier = "getting-to-belem"
    parent = "attending"
    name = "Getting to Belém"
    url = "getting-to-belem/"
    weight = 2

    [[menu.main]]
    identifier = "accommodation"
    parent = "attending"
    name = "Accommodation"
    url = "accommodation/"
    weight = 3

    [[menu.main]]
    identifier = "guided-tours"
    parent = "attending"
    name = "Guided Tours"
    url = "guided-tours/"
    weight = 4

    [[menu.main]]
    identifier = "what-to-do"
    parent = "attending"
    name = "What to do in Belém"
    url = "what-to-do-in-belem/"
    weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_footer = "images/proposta_logo_horizontal_black_bg.png"
logo_width = "180px"
# Meta data
description = "The FOSS4G 2024 conference is taking place 2-8 December in the beautiful city of Belém, Brasil."
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
copyright = "This is a licensed copy allixender@gmail.com for free use in Osgeo projects and events"
# Background Pages Header
backgroundPagesHeader = "images/page-background.jpg"
# Background Footer
backgroundFooter = "images/footer-background.jpg"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Call for papers"
icon = "images/icon/form-icon.png"
link = "call-for-papers/"

# google map
[params.map]
enable = true
#gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "-1.42168"
map_longitude = "-48.45677"
map_marker = "images/marker.png"
name = "Hangar - Convention Center, Belem, PA, Brazil."
location = "Dr. Freitas Avenue - Marco, Belem - PA, 66613-902, Brazil"
email = "foss4g2024@gmail.com "
link = "https://hangarpa.com.br/"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
title = "instagram"
icon = "fa-instagram" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/foss4g"

[[params.social]]
title = "facebook"
icon = "fa-facebook" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/foss4g2024"

[[params.social]]
title = "twitter"
icon = "fa-twitter" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/foss4g"

[[params.social]]
title = "mastodon"
icon = "fa-mastodon" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://fosstodon.org/@foss4g"

[[params.social]]
title = "linkedin"
icon = "fa-linkedin" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/company/foss4g2024"


############################# Languages ##############################
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]

  ######################################
  ############## Español ###############
  ######################################

  [languages.es]
    disabled = false
    languageCode = 'es-AR'
    languageDirection = 'ltr'
    languageName = 'Español'
    title = 'FOSS4G 2024'
    weight = 1

    [languages.es.params.navigation_button]
    enable = true
    label = "Convocatoria de Ponencias"
    icon = "images/icon/form-icon.png"
    link = "convocatoria-de-ponencias/"

    # main menu
    [[languages.es.menu.main]]
    identifier = "home"
    name = "Início"
    url = ""
    weight = 1

    [[languages.es.menu.main]]
    identifier = "about"
    name = "Acerca de"
    url = "acerca-de/"
    weight = 2

        [[languages.es.menu.main]]
        identifier = "organizing-committee"
        parent = "about"
        name = "Comité Organizador"
        url = "comite-organizador/"
        weight = 1

        [[languages.es.menu.main]]
        identifier = "faq"
        parent = "about"
        name = "FAQ"
        url = "faq/"
        weight = 2

        [[languages.es.menu.main]]
        identifier = "branding"
        parent = "about"
        name = "Marca"
        url = "marca/"
        weight = 3

        [[languages.es.menu.main]]
        identifier = "attendee-guidelines"
        parent = "about"
        name = "Normas Para Participantes"
        url = "normas-para-participantes"
        weight = 4

        [[languages.es.menu.main]]
        identifier = "diversity"
        parent = "about"
        name = "Diversidad y Inclusión"
        url = "diversidad-y-inclusion/"
        weight = 5

    [[languages.es.menu.main]]
    identifier = "registration"
    name = "Inscripción"
    url = "inscripcion/"
    weight = 5

    [[languages.es.menu.main]]
    identifier = "schedule"
    name = "Programa"
    url = "programa/"
    weight = 5

        [[languages.es.menu.main]]
        identifier = "keynotes"
        parent = "schedule"
        name = "Keynotes"
        url = "keynotes/"
        weight = 1

        [[languages.es.menu.main]]
        identifier = "b2b"
        parent = "schedule"
        name = "B2B"
        url = "b2b/"
        weight = 2

    [[languages.es.menu.main]]
    identifier = "sponsors"
    name = "Patrocinadores"
    url = "patrocinadores/"
    weight = 6

    [[languages.es.menu.main]]
    identifier = "attending"
    name = "Asistiendo"
    url = "asistiendo/"
    weight = 7

        [[languages.es.menu.main]]
        identifier = "getting-to-belem"
        parent = "attending"
        name = "Llegando a Belém"
        url = "llegando-a-belem/"
        weight = 1

        [[languages.es.menu.main]]
        identifier = "guided-tours"
        parent = "attending"
        name = "Visitas Guiadas"
        url = "visitas-guiadas/"
        weight = 2

  ########################################
  ############## Português ###############
  ########################################

  [languages.pt]
    disabled = false
    languageCode = 'es-AR'
    languageDirection = 'ltr'
    languageName = 'Español'
    title = 'FOSS4G 2024'
    weight = 1

    [languages.pt.params.navigation_button]
    enable = true
    label = "Chamada para Artigos"
    icon = "images/icon/form-icon.png"
    link = "chamada-para-artigos/"

    # main menu
    [[languages.pt.menu.main]]
    identifier = "home"
    name = "Começo"
    url = ""
    weight = 1

    [[languages.pt.menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "sobre/"
    weight = 2

        [[languages.pt.menu.main]]
        identifier = "organizing-committee"
        parent = "about"
        name = "Comitê Organizador"
        url = "comite-organizador/"
        weight = 1

        [[languages.pt.menu.main]]
        identifier = "faq"
        parent = "about"
        name = "FAQ"
        url = "faq/"
        weight = 2

        [[languages.pt.menu.main]]
        identifier = "branding"
        parent = "about"
        name = "Marca"
        url = "marca/"
        weight = 3

        [[languages.pt.menu.main]]
        identifier = "attendee-guidelines"
        parent = "about"
        name = "Regras para Participantes"
        url = "regras-para-participantes"
        weight = 4

        [[languages.pt.menu.main]]
        identifier = "diversity"
        parent = "about"
        name = "Diversidade e Inclusão"
        url = "diversidade-e-inclusao/"
        weight = 5

    [[languages.pt.menu.main]]
    identifier = "registration"
    name = "Registro"
    url = "registro/"
    weight = 5

    [[languages.pt.menu.main]]
    identifier = "schedule"
    name = "Programa"
    url = "programa/"
    weight = 5

        [[languages.pt.menu.main]]
        identifier = "keynotes"
        parent = "schedule"
        name = "Keynotes"
        url = "keynotes/"
        weight = 1

        [[languages.pt.menu.main]]
        identifier = "b2b"
        parent = "schedule"
        name = "B2B"
        url = "b2b/"
        weight = 2

    [[languages.pt.menu.main]]
    identifier = "sponsors"
    name = "Patrocinadores"
    url = "patrocinadores/"
    weight = 6

    [[languages.pt.menu.main]]
    identifier = "attending"
    name = "Atendimento"
    url = "atendimento/"
    weight = 7

        [[languages.pt.menu.main]]
        identifier = "getting-to-belem"
        parent = "attending"
        name = "Chegando em Belém"
        url = "chegando-em-belem/"
        weight = 1

        [[languages.pt.menu.main]]
        identifier = "guided-tours"
        parent = "attending"
        name = "Visitas Guiadas"
        url = "visitas-guiadas/"
        weight = 2