######################## default configuration ####################
baseURL = "https://felipesbarros.github.io/foss4g_template/"
title = "FOSS4G 2024"
theme = "eventre-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/font-awesome/css/all.min.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/mixitup/mixitup.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = ""


####################### navigation ##########################

# main menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

    [[menu.main]]
    parent = "About"
    name = "Organizing committee"
    url = "team/"
    weight = 1

    [[menu.main]]
    parent = "About"
    name = "FAQ"
    url = "faq/"
    weight = 2

    [[menu.main]]
    parent = "About"
    name = "Branding"
    url = "branding/"
    weight = 3

    [[menu.main]]
    parent = "About"
    name = "Attendee Guidelines"
    url = "attendee-guidelines/"
    weight = 4

    [[menu.main]]
    parent = "About"
    name = "Diversity and inclusion"
    url = "diversity/"
    weight = 5

[[menu.main]]
name = "Regstration"
url = "Regstration/"
weight = 5

[[menu.main]]
name = "Schedule"
url = "Schedule/"
weight = 5

    [[menu.main]]
    parent = "Schedule"
    name = "Keynotes"
    url = "Keynotes/"
    weight = 1

    [[menu.main]]
    parent = "Schedule"
    name = "B2B"
    url = "B2B/"
    weight = 2

[[menu.main]]
name = "Sponsors"
url = "sponsors/"
weight = 6

[[menu.main]]
name = "Attending"
url = "Attending/"
weight = 7
hasChildren = true

    [[menu.main]]
    parent = "Attending"
    name = "Getting to Belém"
    url = "getting-to-belem/"
    weight = 1

    [[menu.main]]
    parent = "Attending"
    name = "Guided Tours"
    url = "guided-tours/"
    weight = 2

# [[menu.main]]
# name = "Registration"
# url = "registration/"
# weight = 4
#
#
#  [[menu.main]]
#  parent = "Sponsors"
#  name = "Call for sponsors"
#  url = "call-for-sponsors"
#
#[[menu.main]]
#name = "Schedule"
#url = "Schedule/"
#weight = 5
#
# [[menu.main]]
# weight = 6
# name = "Venue"
# hasChildren = true
#
#  [[menu.main]]
#  parent = "Call for papers"
#  name = "Workshops"
#  url = "cfp-workshops"
#
#  [[menu.main]]
#  parent = "Call for papers"
#  name = "General program"
#  url = "cfp-general-program"
#
#  [[menu.main]]
#  parent = "Call for papers"
#  name = "Academic program"
#  url = "cfp-academic-program"
#
#  [[menu.main]]
#  parent = "Venue"
#  name = "Accommodation"
#  url = "accommodation/"
#
#
#
#
#
#  [[menu.main]]
#  parent = "Venue"
#  name = "Getting to Belém"
#  url = "getting-to-belem/"
#
#  [[menu.main]]
#  parent = "Venue"
#  name = "Attendee guidelines"
#  url = "attendee-guidelines/"
#
#  [[menu.main]]
#  parent = "Venue"
#  name = "About Belém"
#  url = "about-belem/"
#
##  [[menu.main]]
##  parent = "Pages"
##  name = "Pricing"
##  url = "pricing/"
#
##  [[menu.main]]
##  parent = "Pages"
##  name = "Schedule"
##  url = "schedule/"
#
##  [[menu.main]]
##  parent = "Pages"
##  name = "Testimonial"
##  url = "testimonial/"
#
#[[menu.main]]
#name = "Contact"
#url = "contact/"
#weight = 6



#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_footer = "images/proposta_logo_horizontal_black_bg.png"
logo_width = "180px"
# Meta data
description = "The FOSS4G 2024 conference is taking place 2-8 December in the beautiful city of Belém, Brasil."
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
copyright = "This is a licensed copy allixender@gmail.com for free use in Osgeo projects and events"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Call for papers"
icon = "images/icon/form-icon.png"
link = "call-for-papers/"

# Subscription
# [params.subscription]
# enable = true
# title = "Subscribe to Our Newsletter"
# content = "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusm tempor"
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "-1.42168"
map_longitude = "-48.45677"
map_marker = "images/marker.png"
name = "Hangar - Convention Center, Belem, PA, Brazil."
location = "Dr. Freitas Avenue - Marco, Belem - PA, 66613-902, Brazil"
email = "foss4g2024@gmail.com "
link = "https://hangarpa.com.br/"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
title = "instagram"
icon = "fa-instagram" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/foss4g"

[[params.social]]
title = "facebook"
icon = "fa-facebook" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/foss4g2024"

[[params.social]]
title = "twitter"
icon = "fa-twitter" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/foss4g"

[[params.social]]
title = "mastodon"
icon = "fa-mastodon" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://fosstodon.org/@foss4g"

# [[params.social]]
# title = "github"
# icon = "fa-github" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "https://github.com/2024-foss4g-europe/2024-foss4g-europe.github.io"

[[params.social]]
title = "linkedin"
icon = "fa-linkedin" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/company/foss4g2024"
